'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DeliverySheetReceiving

    '''<summary>
    '''btndetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btndetail As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnreset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnreset As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnprocess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnprocess As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblbarcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblbarcode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtbarcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbarcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPONo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPONo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtWhse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWhse As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtvendname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtvendname As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtvendVendInv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtvendVendInv As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTotalLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalLine As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblInvoceAmt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvoceAmt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblVAT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVAT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalInvoice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalInvoice As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PanelList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelList As Global.System.Web.UI.WebControls.ListView

    '''<summary>
    '''lblBarcodeDSNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBarcodeDSNum As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblWebDeliveryReceive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWebDeliveryReceive As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''CountScanLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CountScanLine As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''AmtTotalFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AmtTotalFormat As Global.System.Web.UI.WebControls.HiddenField
End Class
