'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class GenerateGRN
    
    '''<summary>
    '''btndetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btndetail As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnreset control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnreset As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnprocess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnprocess As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblbarcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblbarcode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtbarcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtbarcode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''txtdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlGrnType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlGrnType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtGRN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGRN As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtvendname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtvendname As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtvendVendInv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtvendVendInv As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtWhse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWhse As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtTotalLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalLine As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnvendorlot control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnvendorlot As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''PanelList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelList As Global.System.Web.UI.WebControls.ListView
    
    '''<summary>
    '''lblBarcodeInvNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBarcodeInvNum As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBarcodeInvDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBarcodeInvDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBarcodePoNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBarcodePoNum As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBarcodePoLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBarcodePoLine As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBarcodePoRelease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBarcodePoRelease As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblBarcodeQtyDelivery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBarcodeQtyDelivery As Global.System.Web.UI.WebControls.Label
End Class
