'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Menu
    
    '''<summary>
    '''divJobMonitoring control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divJobMonitoring As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LinkJobMonitoring control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkJobMonitoring As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''divUnposted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divUnposted As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LinkUnpostedJob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkUnpostedJob As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''divPrintProduction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPrintProduction As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LinkPrintProduction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkPrintProduction As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''divJobMatlTran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divJobMatlTran As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LinkJobMatlTran control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkJobMatlTran As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''divJobReceipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divJobReceipt As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LinkJobReceipt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkJobReceipt As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''divPrintWIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPrintWIP As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LinkPrintWIP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkPrintWIP As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''divCycleCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCycleCount As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LinkCycleCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkCycleCount As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''divConfirmShipping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divConfirmShipping As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LinkConfirmShipping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkConfirmShipping As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''divConfirmOrderPick control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divConfirmOrderPick As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LinkConfirmOrderPick control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkConfirmOrderPick As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''divPurchaseOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divPurchaseOrder As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LinkPurchaseOrderRecpt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkPurchaseOrderRecpt As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''divCheckOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCheckOrder As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LinkCheckOrderPickListStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkCheckOrderPickListStatus As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''divQuantityMove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divQuantityMove As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LinkQuantityMove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkQuantityMove As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''divDsReceive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divDsReceive As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''LinkDsReceive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LinkDsReceive As Global.System.Web.UI.WebControls.HyperLink
End Class
